"use client";
import {localRequest} from "@/lib/local-store";
import {useEffect,useState,type FormEvent} from 'react';
import {GraduationCap,LockKeyhole} from 'lucide-react';
import Scheduler from './scheduler';
export default function Home(){
 const [semesters,setSemesters]=useState<{id:number;nome:string}[]>([]),[selectedSemester,setSelectedSemester]=useState('');
 const [canRegister,setCanRegister]=useState(false);
 const [status,setStatus]=useState<'loading'|'login'|'setup'|'ready'|'error'>('loading'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function check(){try{const r=await localRequest('/api/auth',{cache:'no-store'});const data=await r.json() as {error?:string;authenticated?:boolean;needsSetup?:boolean;semestres?:{id:number;nome:string}[]};if(!r.ok)throw Error(data.error);setSemesters(data.semestres||[]);setSelectedSemester(current=>{const saved=current||sessionStorage.getItem('campus_semester');return data.semestres?.some(s=>String(s.id)===saved)?saved!:String(data.semestres?.at(-1)?.id||'')});setCanRegister(!!data.needsSetup);setError('');setStatus(data.authenticated?'ready':'login')}catch{setStatus('error');setError('Não foi possível conectar ao sistema.')}}
 useEffect(()=>{let active=true;localRequest('/api/auth',{cache:'no-store'}).then(async r=>{const data=await r.json() as {authenticated?:boolean;needsSetup?:boolean;semestres?:{id:number;nome:string}[]};if(!r.ok)throw Error();if(active){setSemesters(data.semestres||[]);setSelectedSemester(current=>{const saved=current||sessionStorage.getItem('campus_semester');return data.semestres?.some(s=>String(s.id)===saved)?saved!:String(data.semestres?.at(-1)?.id||'')});setCanRegister(!!data.needsSetup);setStatus(data.authenticated?'ready':'login')}}).catch(()=>{if(active){setStatus('error');setError('Não foi possível conectar ao sistema.')}});return()=>{active=false}},[]);
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setError('');if(status==='setup'&&password!==confirmation){setError('As senhas precisam ser iguais.');return}setBusy(true);try{const r=await localRequest('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:status==='setup'?'setup':'login',username,password})});const data=await r.json() as {error?:string;authenticated?:boolean;needsSetup?:boolean;semestres?:{id:number;nome:string}[]};if(!r.ok)throw Error(data.error);sessionStorage.setItem('campus_semester',selectedSemester);setPassword('');setConfirmation('');setStatus('ready')}catch(e){setError(e instanceof Error?e.message:'Falha ao entrar.')}finally{setBusy(false)}}
 if(status==='ready')return <Scheduler initialSemester={selectedSemester}/>;
 return <main className="login-page"><section className="login-card"><div className="login-brand"><GraduationCap size={30}/><strong>campus</strong></div><span className="eyebrow">GESTÃO ACADÊMICA</span><p className="local-login-note">Dados salvos somente neste navegador. O acesso é local e não criptografa os cadastros. Na primeira visita, crie seu usuário; depois você poderá importar um backup.</p><h1>{status==='setup'?'Criar conta':'Entrar'}</h1><p>{status==='setup'?'Cadastre o usuário e a senha que você usará para acessar sua agenda.':'Entre para organizar aulas, professores e horários.'}</p>{status==='loading'?<p role="status">Verificando acesso...</p>:status==='error'?<button className="primary" onClick={check}>Tentar novamente</button>:<form onSubmit={submit}><fieldset disabled={busy}><label className="field">Semestre<select className="login-semester" aria-label="Semestre de acesso" value={selectedSemester} onChange={e=>setSelectedSemester(e.target.value)} required={semesters.length>0}>{!semesters.length&&<option value="">Nenhum semestre cadastrado</option>}{semesters.map(s=><option key={s.id} value={String(s.id)}>{s.nome}</option>)}</select></label><label className="field">Usuário<input autoComplete="username" required minLength={status==='setup'?3:1} maxLength={80} value={username} onChange={e=>setUsername(e.target.value)}/></label><label className="field">Senha<input type="password" autoComplete={status==='setup'?'new-password':'current-password'} required minLength={status==='setup'?10:1} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label>{status==='setup'&&<><small>Use pelo menos 10 caracteres na senha.</small><label className="field">Confirmar senha<input type="password" autoComplete="new-password" required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label></>}<button className="primary" type="submit"><LockKeyhole size={17}/>{busy?'Aguarde...':status==='setup'?'Criar acesso e entrar':'Entrar'}</button></fieldset></form>}{error&&<p className="form-error" role="alert">{error}</p>}{status==='login'&&canRegister&&<div className="login-registration"><div className="login-divider"><span>Novo no Campus?</span></div><button type="button" className="secondary" disabled={busy} onClick={()=>{setError('');setPassword('');setConfirmation('');setStatus('setup')}}>Criar sua conta</button></div>}{status==='setup'&&<div className="login-registration"><p>Já tem uma conta?</p><button type="button" className="secondary" disabled={busy} onClick={()=>{setError('');setPassword('');setConfirmation('');setStatus('login')}}>Voltar para o login</button></div>}</section></main>
}
