"use client";
import {useMemo,useState} from 'react';
import {Search,ChevronDown,ChevronRight,Clock} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {teacherWorkloads} from '@/lib/workload';
import {normalize,type Data} from '@/lib/schedule';
const number=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:2});
const duration=(n:number)=>`${Math.floor(n/60)}h${n%60?` ${n%60}min`:''}`;
export function TeacherWorkload({data,semester,onSemesterChange,loading}:{data:Data;semester:string;onSemesterChange:(v:string)=>void;loading:boolean}){
 const [query,setQuery]=useState(''),[expanded,setExpanded]=useState<number|null>(null);
 const current=data.semestres.some(s=>String(s.id)===semester)?semester:String(data.semestres.at(-1)?.id||'');
 const rows=useMemo(()=>teacherWorkloads(data,Number(current)).filter(r=>normalize(r.teacher.nome).includes(normalize(query))),[data,current,query]);
 return <section className="data-panel teacher-workload"><div className="filters"><label>Semestre<Select value={current} onValueChange={v=>{onSemesterChange(v);setExpanded(null)}}><SelectTrigger aria-label="Semestre da carga horária"><SelectValue placeholder="Selecione o semestre"/></SelectTrigger><SelectContent>{data.semestres.map(s=><SelectItem key={s.id} value={String(s.id)}>{s.nome}</SelectItem>)}</SelectContent></Select></label><label className="searchbox"><Search size={17}/><input aria-label="Buscar professor na carga horária" placeholder="Buscar professor..." value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="calendar-toolbar"><div><Clock size={18}/><strong>Carga horária por professor</strong><span>{rows.length} docentes</span></div></div><p className="workload-explanation">Aulas semanais não incluem intervalos. A carga horária é somada por disciplina e turma; quando há mais de um professor, é dividida conforme as aulas atribuídas.</p>{loading?<div className="loading-state" role="status">Carregando cargas horárias...</div>:!current?<Empty><EmptyHeader><EmptyTitle>Cadastre um semestre</EmptyTitle><EmptyDescription>Os totais aparecem após cadastrar o semestre e os horários das aulas.</EmptyDescription></EmptyHeader></Empty>:!rows.length?<Empty><EmptyHeader><EmptyTitle>Nenhum professor encontrado</EmptyTitle><EmptyDescription>Altere a busca ou adicione docentes em Cadastros.</EmptyDescription></EmptyHeader></Empty>:<Table><TableHeader><TableRow><TableHead>Professor</TableHead><TableHead>Disciplinas / turmas</TableHead><TableHead>Aulas semanais</TableHead><TableHead>Tempo em aula / semana</TableHead><TableHead>Carga horária atribuída</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><WorkloadRows key={r.teacher.id} row={r} expanded={expanded===r.teacher.id} toggle={()=>setExpanded(expanded===r.teacher.id?null:r.teacher.id)}/>)}</TableBody></Table>}</section>
}
function WorkloadRows({row:r,expanded,toggle}:{row:ReturnType<typeof teacherWorkloads>[number];expanded:boolean;toggle:()=>void}){return <><TableRow><TableCell><button className="workload-teacher" onClick={toggle} aria-expanded={expanded} aria-label={`Ver disciplinas de ${r.teacher.nome}`}>{expanded?<ChevronDown size={17}/>:<ChevronRight size={17}/>}<strong>{r.teacher.nome}</strong></button></TableCell><TableCell>{r.assignments.length}</TableCell><TableCell>{r.weekly}</TableCell><TableCell>{duration(r.minutes)}</TableCell><TableCell><strong>{number(r.hours)} h</strong>{r.missing&&<small className="workload-warning">Total parcial: falta carga cadastrada</small>}</TableCell><TableCell><span className={`workload-status ${r.pending||r.missing?'pending':''}`}>{r.pending?'Distribuição incompleta':r.missing?'Carga não informada':!r.assignments.length?'Sem aulas':'Distribuição completa'}</span></TableCell></TableRow>{expanded&&<TableRow className="workload-expanded"><TableCell colSpan={6}>{!r.assignments.length?<p>Este professor não possui aulas no semestre selecionado.</p>:<div className="workload-details">{r.assignments.map(a=><div key={a.key}><div><strong>{a.disciplina}{a.codigo?` · ${a.codigo}`:''}</strong><span>{a.turma}</span></div><span>{a.weekly} aulas/semana</span><strong>{a.hours===null?'Carga não informada':`${number(a.hours)} h`}</strong>{!a.complete&&<small>Turma com {a.groupWeekly} de {a.expected} aulas obrigatórias</small>}</div>)}</div>}</TableCell></TableRow>}</>}
