import {ShieldCheck,TriangleAlert} from 'lucide-react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {time,shiftLabel,type Aula,type Conflict,type Entity} from '@/lib/schedule';
import {schedulePeriods,periodsForShift} from '@/lib/periods';
export function Timetable({aulas,alertMap,onSelect,heading,printShift,disciplinas=[],turmas=[]}:{turmas?:Entity[];printShift?:string;disciplinas?:Entity[];heading?:string;aulas:Aula[];alertMap:Map<number,Conflict[]>;onSelect:(a:Aula)=>void}){
 const weekDays=['SEG','TER','QUA','QUI','SEX','SÁB'];

 return <div className="academic-grid"><Table aria-label="Agenda semanal por faixas de horário">{heading&&<colgroup><col style={{width:"6%"}}/>{weekDays.map(day=><col key={day} style={{width:`${94/weekDays.length}%`}}/>)}</colgroup>}<TableHeader>{heading&&<TableRow className="print-group-title"><TableHead colSpan={weekDays.length+1}>{heading}</TableHead></TableRow>}<TableRow><TableHead scope="col">HORÁRIO</TableHead>{weekDays.map(day=><TableHead scope="col" key={day}><strong>{day}</strong></TableHead>)}</TableRow></TableHeader><TableBody>{(printShift?periodsForShift(printShift):schedulePeriods(aulas)).map(period=><TableRow key={period.start} className={period.break?'period-break':''}><TableHead scope="row" className="period-label">{time(period.start)}<span className="period-dash">–</span>{time(period.end)}</TableHead>{weekDays.map((day,index)=>{const matches=period.break?[]:aulas.filter(a=>a.dia_semana===index+1&&a.hora_inicio<period.end&&a.hora_fim>period.start);return <TableCell key={day}>{period.break&&<span className="break-label">INTERVALO</span>}{matches.map(a=><button key={a.id} className={`grid-class shift-${a.turno==='Manhã'?'morning':a.turno==='Tarde'?'afternoon':'night'} ${alertMap.get(a.id)?.length?'grid-conflict':''}`} onClick={()=>onSelect(a)} aria-label={`${a.disciplina}, ${a.docente}, ${time(a.hora_inicio)} às ${time(a.hora_fim)}`} title={`${a.turma} · ${a.sala} · ${time(a.hora_inicio)}–${time(a.hora_fim)}`}><strong>{a.disciplina}{disciplinas.find(d=>d.id===a.disciplina_id)?.codigo&&<> - {disciplinas.find(d=>d.id===a.disciplina_id)?.codigo}</>}</strong><span className="grid-professor">{a.docente}</span><span className="grid-details">{(a.semestre_curso??turmas.find(t=>t.id===a.turma_id)?.semestre_curso)?`${a.semestre_curso??turmas.find(t=>t.id===a.turma_id)?.semestre_curso}º semestre`:'Semestre não informado'} · {shiftLabel(a.turno)}</span>{!!alertMap.get(a.id)?.length&&<TriangleAlert aria-label="Conflito de horário" size={14}/>}</button>)}</TableCell>})}</TableRow>)}</TableBody></Table><div className="calendar-legend"><div><span className="legend-dot morning"/>Matutino<span className="legend-dot afternoon"/>Vespertino<span className="legend-dot night"/>Noturno</div><span><ShieldCheck size={14}/>Conflitos verificados ao salvar</span></div></div>;
}

