import {authenticated} from '@/lib/auth';
import {saveWeekly} from './weekly';
import {requiredClassPeriods} from '@/lib/periods';
import {validClassTimes} from '@/lib/periods';
import {z} from "zod";
import {database} from "@/db/connection";
import {conflicts,kinds,normalize,type Aula,type Data} from "@/lib/schedule";
export const dynamic="force-dynamic";
const joined=`SELECT a.*,d.nome docente,p.nome disciplina,COALESCE(t.nome,'Sem turma') turma,s.nome sala,e.nome semestre FROM aulas a JOIN docentes d ON d.id=a.docente_id JOIN disciplinas p ON p.id=a.disciplina_id LEFT JOIN turmas t ON t.id=a.turma_id JOIN salas s ON s.id=a.sala_id JOIN semestres e ON e.id=a.semestre_id`;
const id=z.number().int().positive();
const aulaSchema=z.object({id:id.optional(),docente_id:id,disciplina_id:id,turma_id:id.nullable().default(null),sala_id:id,semestre_id:id,semestre_curso:z.number().int().min(1).max(20),turno:z.enum(["Manhã","Tarde","Noite"]),dia_semana:z.number().int().min(1).max(6),hora_inicio:z.number().int().min(420).max(1319),hora_fim:z.number().int().min(421).max(1320)}).refine(v=>v.hora_fim>v.hora_inicio,{message:"O horário final deve ser maior que o inicial."});
function json(data:unknown,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store"}})}
async function getConflicts(v:z.infer<typeof aulaSchema>){const rows=await database().prepare(joined+" WHERE a.semestre_id=? AND a.dia_semana=? AND a.hora_inicio<? AND a.hora_fim>? AND a.id<>?").bind(v.semestre_id,v.dia_semana,v.hora_fim,v.hora_inicio,v.id||0).all<Aula>();return conflicts(v,rows.results)}
export async function GET(request:Request){try{if(!await authenticated(request))return json({error:"Entre para acessar a agenda."},401);const db=database();const results=await db.batch([db.prepare(joined+" ORDER BY a.dia_semana,a.hora_inicio,a.id"),...kinds.map(k=>db.prepare(`SELECT id,nome${k==='disciplinas'?',codigo,carga_horaria':k==='turmas'?',semestre_curso':''} FROM ${k} ORDER BY nome COLLATE NOCASE`))]);const data={aulas:results[0].results} as Data;kinds.forEach((k,i)=>{data[k]=results[i+1].results as any});return json(data)}catch(e){console.error("Load schedule",e);return json({error:"Não foi possível carregar a agenda. Tente novamente."},503)}}
export async function POST(request:Request){try{if(!await authenticated(request))return json({error:"Entre para acessar a agenda."},401);
 const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return json({error:"Origem não autorizada."},403);
 const body=z.record(z.unknown()).parse(await request.json());const db=database();
 if(body.action==='save_weekly')return await saveWeekly(body.data);
 if(body.action==='delete_weekly'){const target=id.parse(body.id);await db.prepare('DELETE FROM aulas WHERE EXISTS (SELECT 1 FROM aulas target WHERE target.id=? AND aulas.disciplina_id=target.disciplina_id AND aulas.semestre_id=target.semestre_id AND aulas.turma_id IS target.turma_id AND aulas.semestre_curso IS target.semestre_curso AND (target.turma_id IS NOT NULL OR aulas.docente_id=target.docente_id))').bind(target).run();return json({ok:true})}
 if(body.action==="save_aula"){
 const parsed=aulaSchema.safeParse(body.data);if(!parsed.success)return json({error:parsed.error.issues[0].message==="O horário final deve ser maior que o inicial."?parsed.error.issues[0].message:"Preencha todos os campos e use horários entre 07:00 e 22:00."},400);const v=parsed.data;if(!validClassTimes(v.hora_inicio,v.hora_fim))return json({error:"Selecione início e término entre os horários da grade."},400);
 if(v.id&&!await db.prepare("SELECT id FROM aulas WHERE id=?").bind(v.id).first())return json({error:"Esta aula não existe mais. Atualize a agenda."},404);
 const checks=await db.batch(kinds.flatMap((k,i)=>k==='turmas'&&v.turma_id===null?[]:[db.prepare(`SELECT id FROM ${k} WHERE id=?`).bind([v.docente_id,v.disciplina_id,v.turma_id,v.sala_id,v.semestre_id][i])]));if(checks.some(r=>!r.results.length))return json({error:"Um cadastro selecionado não existe mais. Atualize a agenda."},400);
 const course=await db.prepare('SELECT carga_horaria FROM disciplinas WHERE id=?').bind(v.disciplina_id).first<{carga_horaria:number|null}>();
 if(requiredClassPeriods(course?.carga_horaria))return json({error:'Salve a distribuição semanal completa desta disciplina (4 aulas para 60h ou 6 aulas para 90h).'},400);
 if(v.id){const original=await db.prepare('SELECT p.carga_horaria FROM aulas a JOIN disciplinas p ON p.id=a.disciplina_id WHERE a.id=?').bind(v.id).first<{carga_horaria:number|null}>();if(requiredClassPeriods(original?.carga_horaria))return json({error:'Edite a distribuição semanal completa para manter a quantidade obrigatória de aulas.'},400)}
 const found=await getConflicts(v);if(found.length)return json({error:"Conflito de horário",conflicts:found},409);
 const values=[v.docente_id,v.disciplina_id,v.turma_id,v.sala_id,v.semestre_id,v.turno,v.dia_semana,v.hora_inicio,v.hora_fim,v.semestre_curso];
 try{const result=v.id?await db.prepare("UPDATE aulas SET docente_id=?,disciplina_id=?,turma_id=?,sala_id=?,semestre_id=?,turno=?,dia_semana=?,hora_inicio=?,hora_fim=?,semestre_curso=? WHERE id=?").bind(...values,v.id).run():await db.prepare("INSERT INTO aulas(docente_id,disciplina_id,turma_id,sala_id,semestre_id,turno,dia_semana,hora_inicio,hora_fim,semestre_curso) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(...values).run();if(v.id && !result.meta.changes)return json({error:"Esta aula foi excluída. Atualize a agenda."},404);return json({ok:true,id:v.id||result.meta.last_row_id})}catch(e){if(String(e).includes("SCHEDULE_CONFLICT"))return json({error:"Outro cadastro ocupou este horário. Revise os conflitos e tente novamente.",conflicts:await getConflicts(v)},409);throw e}
 }
 if(body.action==="delete_aula"){const key=id.parse(body.id);const course=await db.prepare('SELECT p.carga_horaria FROM aulas a JOIN disciplinas p ON p.id=a.disciplina_id WHERE a.id=?').bind(key).first<{carga_horaria:number|null}>();if(requiredClassPeriods(course?.carga_horaria))return json({error:'Exclua a distribuição completa ou edite seus horários para manter a quantidade obrigatória de aulas.'},400);await db.prepare("DELETE FROM aulas WHERE id=?").bind(key).run();return json({ok:true})}
 const kind=z.enum(kinds).parse(body.kind);
 if(body.action==="save_entity"){const name=z.string().trim().min(1).max(100).parse(body.nome).replace(/\s+/g," ");if(kind==="semestres"&&!/^\d{4}\.[123]$/.test(name))return json({error:"Use o formato 2026.1, 2026.2 ou 2026.3 para o semestre."},400);const key=body.id===undefined?undefined:id.parse(body.id);const dup=await db.prepare(`SELECT id FROM ${kind} WHERE chave=? AND id<>?`).bind(normalize(name),key||0).first();if(dup)return json({error:"Já existe um cadastro com este nome."},409);if(kind==='turmas'){const parsed=z.number().int().min(1).max(20).nullable().optional().safeParse(body.semestre_curso);if(!parsed.success)return json({error:'Informe um semestre do curso entre 1 e 20.'},400);const semestre=parsed.data??null;const r=key?await db.prepare('UPDATE turmas SET nome=?,chave=?,semestre_curso=? WHERE id=?').bind(name,normalize(name),semestre,key).run():await db.prepare('INSERT INTO turmas(nome,chave,semestre_curso) VALUES(?,?,?)').bind(name,normalize(name),semestre).run();if(key&&!r.meta.changes)return json({error:'Cadastro não encontrado.'},404);return json({ok:true,id:key||r.meta.last_row_id})}if(kind==='disciplinas'){const fields=z.object({codigo:z.string().trim().min(1).max(40),carga_horaria:z.number().int().positive().max(10000)}).safeParse(body);if(!fields.success)return json({error:'Informe o código e uma carga horária inteira maior que zero.'},400);const {codigo,carga_horaria}=fields.data;if(key){const old=await db.prepare('SELECT carga_horaria FROM disciplinas WHERE id=?').bind(key).first<{carga_horaria:number|null}>();if(old?.carga_horaria!==carga_horaria&&await db.prepare('SELECT id FROM aulas WHERE disciplina_id=? LIMIT 1').bind(key).first())return json({error:'Esta disciplina já possui horários. Remova sua distribuição antes de alterar a carga horária.'},409)}const r=key?await db.prepare('UPDATE disciplinas SET nome=?,chave=?,codigo=?,carga_horaria=? WHERE id=?').bind(name,normalize(name),codigo,carga_horaria,key).run():await db.prepare('INSERT INTO disciplinas(nome,chave,codigo,carga_horaria) VALUES(?,?,?,?)').bind(name,normalize(name),codigo,carga_horaria).run();if(key&&!r.meta.changes)return json({error:'Cadastro não encontrado.'},404);return json({ok:true,id:key||r.meta.last_row_id})}if(key){const r=await db.prepare(`UPDATE ${kind} SET nome=?,chave=? WHERE id=?`).bind(name,normalize(name),key).run();if(!r.meta.changes)return json({error:"Cadastro não encontrado."},404);return json({ok:true,id:key})}const r=await db.prepare(`INSERT INTO ${kind}(nome,chave) VALUES(?,?)`).bind(name,normalize(name)).run();return json({ok:true,id:r.meta.last_row_id})}
 if(body.action==="delete_entity"){await db.prepare(`DELETE FROM ${kind} WHERE id=?`).bind(id.parse(body.id)).run();return json({ok:true})}
 return json({error:"Operação inválida."},400);
 }catch(e){if(e instanceof z.ZodError||e instanceof SyntaxError)return json({error:"Confira os dados informados."},400);if(String(e).includes("FOREIGN KEY"))return json({error:"Este cadastro está vinculado a aulas. Edite ou exclua essas aulas primeiro."},409);if(String(e).includes("UNIQUE"))return json({error:"Já existe um cadastro com este nome."},409);console.error("Save schedule",e);return json({error:"Não foi possível salvar. Seus dados foram preservados; tente novamente."},503)}}


